#include "engine/world/cell_state.h"
#include <nlohmann/json.hpp>
#include <windows.h>
#include <cmath>
#include <fstream>
namespace engine { namespace { EngineError err(std::string c,std::string m){return {std::move(c),Severity::Error,ErrorCategory::Serialization,"cell-state",std::move(m),ENGINE_SOURCE_CONTEXT,{},"Repair metadata or restore the backup.",make_correlation_id()};} }
Result<void> TerrainTileMetadata::validate() const { if(height_resolution<3||height_resolution>4097||((height_resolution-1)&(height_resolution-2))!=0)return Result<void>::failure(err("TERRAIN-RESOLUTION-INVALID","Resolution must be 2^n+1")); if(!std::isfinite(minimum_height)||!std::isfinite(maximum_height)||minimum_height>maximum_height)return Result<void>::failure(err("TERRAIN-HEIGHT-RANGE-INVALID","Invalid height range")); if(height_asset.empty())return Result<void>::failure(err("TERRAIN-HEIGHT-ASSET-MISSING","Height asset is required")); return Result<void>::success(); }
Result<std::set<CellCoord>> simulation_bubble(CellCoord c,std::uint32_t radius){if(radius>32)return Result<std::set<CellCoord>>::failure(err("SIMULATION-RADIUS-INVALID","Radius exceeds 32"));std::set<CellCoord>s;auto r=static_cast<std::int32_t>(radius);for(std::int32_t z=-r;z<=r;++z)for(std::int32_t x=-r;x<=r;++x)if(x*x+z*z<=r*r)s.insert({c.x+x,c.z+z});return Result<std::set<CellCoord>>::success(std::move(s));}
void CellStateStore::set(CellCoord c,std::string k,std::string v){states_[c][std::move(k)]=std::move(v);} std::optional<std::string> CellStateStore::get(CellCoord c,const std::string&k)const{auto a=states_.find(c);if(a==states_.end())return{};auto b=a->second.find(k);return b==a->second.end()?std::nullopt:std::optional<std::string>(b->second);}
std::string CellStateStore::to_json()const{nlohmann::ordered_json r{{"schemaVersion",1},{"cells",nlohmann::ordered_json::array()}};for(const auto&c:states_)r["cells"].push_back({{"x",c.first.x},{"z",c.first.z},{"values",c.second}});return r.dump(2)+"\n";}
Result<CellStateStore> CellStateStore::from_json(const std::string&t){try{auto r=nlohmann::json::parse(t);if(r.value("schemaVersion",0)!=1||!r["cells"].is_array())return Result<CellStateStore>::failure(err("CELL-STATE-SCHEMA","Invalid schema"));CellStateStore s;for(const auto&c:r["cells"])s.states_[{c.at("x"),c.at("z")}]=c.at("values").get<std::map<std::string,std::string>>();return Result<CellStateStore>::success(std::move(s));}catch(const std::exception&e){auto x=err("CELL-STATE-JSON","Malformed JSON");x.causes.push_back(e.what());return Result<CellStateStore>::failure(std::move(x));}}
Result<CellStateStore> CellStateStore::load(const std::filesystem::path&p){std::ifstream i(p,std::ios::binary);if(!i)return Result<CellStateStore>::failure(err("CELL-STATE-READ","Cannot read state"));return from_json({std::istreambuf_iterator<char>(i),{}});}
Result<void> CellStateStore::save_atomic(const std::filesystem::path&p)const{try{if(p.has_parent_path())std::filesystem::create_directories(p.parent_path());auto t=std::filesystem::path(p.string()+".tmp");{std::ofstream o(t,std::ios::binary|std::ios::trunc);o<<to_json();if(!o)throw std::runtime_error("write");}if(std::filesystem::exists(p)){auto b=std::filesystem::path(p.string()+".bak");if(!ReplaceFileW(p.c_str(),t.c_str(),b.c_str(),REPLACEFILE_WRITE_THROUGH,nullptr,nullptr))throw std::runtime_error("replace");}else if(!MoveFileExW(t.c_str(),p.c_str(),MOVEFILE_WRITE_THROUGH))throw std::runtime_error("move");return Result<void>::success();}catch(const std::exception&e){auto x=err("CELL-STATE-WRITE","Atomic save failed");x.causes.push_back(e.what());return Result<void>::failure(std::move(x));}}
}
